//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUISignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public string ConnectionId { get; set; }
        public int UserUserId { get; set; }
        public bool Connected { get; set; }
    
        public virtual User User { get; set; }
    }
}
